/* Generated By:JJTree&JavaCC: Do not edit this line. LanguageConstants.java */
package wci.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int IGNORE2 = 2;
  /** RegularExpression Id. */
  int LETTER = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int WORD = 5;
  /** RegularExpression Id. */
  int URL = 6;
  /** RegularExpression Id. */
  int DOMAIN = 7;
  /** RegularExpression Id. */
  int BOOLEAN = 8;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int REAL = 12;
  /** RegularExpression Id. */
  int FOREACH = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int ELSEIF = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int FUNCTION = 19;
  /** RegularExpression Id. */
  int VOID = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int DISPLAY = 22;
  /** RegularExpression Id. */
  int BOOLEAN_TYPE = 23;
  /** RegularExpression Id. */
  int DOMAIN_TYPE = 24;
  /** RegularExpression Id. */
  int INTEGER_TYPE = 25;
  /** RegularExpression Id. */
  int INTEGER_LIST_TYPE = 26;
  /** RegularExpression Id. */
  int REAL_LIST_TYPE = 27;
  /** RegularExpression Id. */
  int STRING_LIST_TYPE = 28;
  /** RegularExpression Id. */
  int REAL_TYPE = 29;
  /** RegularExpression Id. */
  int STRING_TYPE = 30;
  /** RegularExpression Id. */
  int URL_TYPE = 31;
  /** RegularExpression Id. */
  int LESS_EQUALS = 32;
  /** RegularExpression Id. */
  int GREATER_EQUALS = 33;
  /** RegularExpression Id. */
  int PLUS_EQUALS = 34;
  /** RegularExpression Id. */
  int MINUS_EQUALS = 35;
  /** RegularExpression Id. */
  int STAR_EQUALS = 36;
  /** RegularExpression Id. */
  int EQUALS = 37;
  /** RegularExpression Id. */
  int MODULUS_EQUALS = 38;
  /** RegularExpression Id. */
  int NOT_EQUALS = 39;
  /** RegularExpression Id. */
  int MODULUS = 40;
  /** RegularExpression Id. */
  int STAR = 41;
  /** RegularExpression Id. */
  int DIVIDE = 42;
  /** RegularExpression Id. */
  int MINUS = 43;
  /** RegularExpression Id. */
  int PLUS = 44;
  /** RegularExpression Id. */
  int ASSIGNMENT = 45;
  /** RegularExpression Id. */
  int SEMICOLON = 46;
  /** RegularExpression Id. */
  int LESS_THAN = 47;
  /** RegularExpression Id. */
  int GREATER_THAN = 48;
  /** RegularExpression Id. */
  int QUOTATION_MARK = 49;
  /** RegularExpression Id. */
  int LEFT_PAREN = 50;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 51;
  /** RegularExpression Id. */
  int LEFT_BRACE = 52;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 53;
  /** RegularExpression Id. */
  int DOT = 54;
  /** RegularExpression Id. */
  int DOLLAR_SIGN = 55;
  /** RegularExpression Id. */
  int COLON = 56;
  /** RegularExpression Id. */
  int COMMA = 57;
  /** RegularExpression Id. */
  int OPBR = 58;
  /** RegularExpression Id. */
  int CLBR = 59;
  /** RegularExpression Id. */
  int IDENTIFIER = 60;
  /** RegularExpression Id. */
  int ERROR = 61;
  /** RegularExpression Id. */
  int EOL = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "<IGNORE2>",
    "<LETTER>",
    "<DIGIT>",
    "<WORD>",
    "<URL>",
    "<DOMAIN>",
    "<BOOLEAN>",
    "<SINGLE_LINE_COMMENT>",
    "<STRING>",
    "<INTEGER>",
    "<REAL>",
    "\"foreach\"",
    "\"in\"",
    "\"else\"",
    "\"elseif\"",
    "\"if\"",
    "\"for\"",
    "\"function\"",
    "\"void\"",
    "\"return\"",
    "\"display\"",
    "\"Boolean\"",
    "\"Domain\"",
    "\"Integer\"",
    "\"List[Integer]\"",
    "\"List[Real]\"",
    "\"List[String]\"",
    "\"Real\"",
    "\"String\"",
    "\"Url\"",
    "\"<=\"",
    "\">=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"==\"",
    "\"%=\"",
    "\"<>\"",
    "\"%\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"+\"",
    "\"=\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"$\"",
    "\":\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<IDENTIFIER>",
    "<ERROR>",
    "<EOL>",
  };

}
