/* Generated By:JavaCC: Do not edit this line. LanguageVisitor.java Version 5.0 */
package wci.frontend;

public interface LanguageVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTStatementList node, Object data);
  public Object visit(ASTTypeSpec node, Object data);
  public Object visit(ASTdisplay node, Object data);
  public Object visit(ASTFor node, Object data);
  public Object visit(ASTIF node, Object data);
  public Object visit(ASTELSEIF node, Object data);
  public Object visit(ASTELSE node, Object data);
  public Object visit(ASTRelOp node, Object data);
  public Object visit(ASTAssignmentStatement node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTFuncCall node, Object data);
  public Object visit(ASTFuncVar node, Object data);
  public Object visit(ASTFuncParams node, Object data);
  public Object visit(ASTFuncReturnType node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSubtract node, Object data);
  public Object visit(ASTMultOp node, Object data);
  public Object visit(ASTDivOp node, Object data);
  public Object visit(ASTRelationalOp node, Object data);
  public Object visit(ASTListSize node, Object data);
  public Object visit(ASTlistItemType node, Object data);
  public Object visit(ASTListIndex node, Object data);
  public Object visit(ASTintegerConstant node, Object data);
  public Object visit(ASTrealConstant node, Object data);
  public Object visit(ASTstringConstant node, Object data);
}
/* JavaCC - OriginalChecksum=55fb3978ab7700e40a3423050df791d1 (do not edit this line) */
