/* Generated By:JavaCC: Do not edit this line. LanguageTreeConstants.java Version 5.0 */
package wci.frontend;

public interface LanguageTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENTLIST = 1;
  public int JJTVOID = 2;
  public int JJTTYPESPEC = 3;
  public int JJTDISPLAY = 4;
  public int JJTFOR = 5;
  public int JJTIF = 6;
  public int JJTELSEIF = 7;
  public int JJTELSE = 8;
  public int JJTRELOP = 9;
  public int JJTASSIGNMENTSTATEMENT = 10;
  public int JJTVARIABLE = 11;
  public int JJTFUNC = 12;
  public int JJTFUNCCALL = 13;
  public int JJTFUNCVAR = 14;
  public int JJTFUNCPARAMS = 15;
  public int JJTFUNCRETURNTYPE = 16;
  public int JJTADD = 17;
  public int JJTSUBTRACT = 18;
  public int JJTMULTOP = 19;
  public int JJTDIVOP = 20;
  public int JJTRELATIONALOP = 21;
  public int JJTLISTSIZE = 22;
  public int JJTLISTITEMTYPE = 23;
  public int JJTLISTINDEX = 24;
  public int JJTINTEGERCONSTANT = 25;
  public int JJTREALCONSTANT = 26;
  public int JJTSTRINGCONSTANT = 27;


  public String[] jjtNodeName = {
    "Program",
    "StatementList",
    "void",
    "TypeSpec",
    "display",
    "For",
    "IF",
    "ELSEIF",
    "ELSE",
    "RelOp",
    "AssignmentStatement",
    "Variable",
    "Func",
    "FuncCall",
    "FuncVar",
    "FuncParams",
    "FuncReturnType",
    "Add",
    "Subtract",
    "MultOp",
    "DivOp",
    "RelationalOp",
    "ListSize",
    "listItemType",
    "ListIndex",
    "integerConstant",
    "realConstant",
    "stringConstant",
  };
}
/* JavaCC - OriginalChecksum=f045ccbf27fbee0efd8bdfff09005c57 (do not edit this line) */
